version: "3"

services:
  wd-forecast-server:
    build:
      context: .
      dockerfile: ./docker-file
    image: py37:1.20
    container_name: station-base-micro-server
    working_dir: /opt/project
    privileged: true
    ports:
      - "8088:8088"
    command:
      - /bin/bash
    tty: true
    volumes:
      - /home/surge/proj/station_base_micro_server/server:/opt/project


